ALTER TABLE IF EXISTS user_profiles
  ADD COLUMN IF NOT EXISTS avatar_url TEXT NULL;

ALTER TABLE IF EXISTS listings
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS google_maps_place_id VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS google_maps_url TEXT NULL;
